#spring.profiles.active=dev
# 所有环境通用的配置，放在这里

# 404 交给异常处理器处理
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false
spring:
  freemarker:
    suffix: .html
    charset: UTF-8
    cache: false #缓存配置
    content-type: text/html
    enabled: true
    request-context-attribute: req  #req访问request
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    settings:
      number_format: '0.##' #数字格式化，无小数点

#  zipkin:
#    base-url: http://localhost:8003
  sleuth:
    sampler:
      percentage: 1.0 #指定按需采样的请求的百分比
#  profiles:
#    active: dev
  application:
    name: webapp

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin

server:
  port: 9081
  context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true

##饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: ucenter
security:
  oauth2:
    resource:
      id: webapp
      user-info-uri: http://localhost:8002/uaa/user
      prefer-token-info: false
    sso:
      login-path: http://localhost:8002/uaa/login

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
