#spring.profiles.active=dev
# 所有环境通用的配置，放在这里

# 404 交给异常处理器处理
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false
spring:
  freemarker:
    suffix: .html
    charset: UTF-8
    cache: false #缓存配置
    content-type: text/html
    enabled: true
    request-context-attribute: req  #req访问request
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    settings:
      number_format: '0.##' #数字格式化，无小数点
  profiles:
    active: dev
  application:
    name: webapp

server:
  port: 9081
  context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true # 表示将自己的ip注册到eureka server

feign:
  hystrix:
   enabled: true


