server:
  port: 8002
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    ucenter:
      path: /ucenter/**
      stripPrefix: true
      serviceId: ucenter
    api-gateway:
      path: /api-gateway/**
      stripPrefix: true
      serviceId: api-gateway
  ignored-services: '*'
#  ribbon:
#    eager-load:
#      enabled: true

#feign:
#  hystrix:
#    enabled: true




