server:
  port: 8002
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false
#zuul:
#  routes:
#    ucenter:
#      path: /ucenter/**
#      stripPrefix: true
#      serviceId: ucenter
#    api-gateway:
#      path: /api-gateway/**
#      stripPrefix: true
#      serviceId: api-gateway
#  ignored-services: '*'

#饥饿加载
zuul:
  ribbon:
    eager-load:
      enabled: true

#feign:
#  hystrix:
#    enabled: true

#超时配置
#ribbon:
#  ReadTimeout:100
#  ConnectTimeout:500
#  MaxAutoRetries:1
#  MaxAutoRetriesNextServer:1


