spring:
  application:
    name: ucenter
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
  jpa:
  #  show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
#  zipkin:
#    base-url: http://localhost:8003
  sleuth:
    sampler:
      percentage: 1.0 #指定按需采样的请求的百分比
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin

server:
  port: 9080
  #context-path: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG

security:
  oauth2:
    resource:
      id: ucenter
      user-info-uri: http://localhost:8002/uaa/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG
management.security.enabled: false