spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
  jpa:
  #  show-sql: true
    hibernate:
      ddl-auto: none
